# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20170919_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
