# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 09:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20170919_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='timestamp',
            new_name='release_date',
        ),
    ]
